name: "FAP: Build"

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show files
        run: |
          echo "Repo root:"
          ls -la
          echo "App dir:"
          ls -la chaos_pet

      - name: Build with uFBT
        id: build-app
        uses: flipperdevices/flipperzero-ufbt-action@v0.1.4
        with:
          sdk-channel: release
          app-dir: chaos_pet

      - name: Upload FAP artifact
        uses: actions/upload-artifact@v4
        with:
          name: chaos_pet_fap
          path: ${{ steps.build-app.outputs.fap-artifacts }}
